### ISSUE TITLE
Does not work with python 3.8

### ISSUE THREAD

**Issue by jrosiek** [dvdotsenko/python-future-then#1]
```
# ...
File ".../python3.8/site-packages/futures_then/futures_then.py", line 157, in _done_handler
    new_future.set_exception_info(ex, trace_back)
AttributeError: 'ThenableFuture' object has no attribute 'set_exception_info'
```
